export {default as Home} from './Home'
export {default as Profile} from './Profile'
export {default as Messages} from './Messages'
export {default as Moments} from './Moments'
export {default as Settings} from './Settings'